Header header
---
float64[] cameraXPositions
float64[] cameraYPositions
float64[] cameraZPositions
float64[] cameraRotationMatrices # Contains the 3x3 rotation matrices for the cameras.
                                 # Every matrix has 9 entries row by row.
uint32[] IDs
