Header header
uint32 chessboardWidth # The amount of horizontal corners of the chessboard.
uint32 chessboardHeight # The amount of vertical corners of the chessboard.
float64 chessboardRealWidth # The width of one chessboard field.
float64 chessboardRealHeight # The height of one chessboard field.
---
bool ok